import type { ArchLensProject } from '../domain/types';

export const EXAMPLE_PROJECT: ArchLensProject = {
  version: '1.0.0',
  name: 'Loyalty Rewards Platform',
  description: 'An enterprise loyalty program with points, tiers, personalized offers, and AI-driven engagement',
  createdAt: '2026-06-01T00:00:00.000Z',
  updatedAt: '2026-06-01T00:00:00.000Z',
  entities: [
    // ════════════════════════════════════════════════════════════════
    // BUSINESS viewpoint · context level  (person, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'p-member',
      name: 'Loyalty Member',
      shortName: 'Mbr',
      description: 'End user enrolled in the loyalty program who earns and redeems points',
      kind: 'person',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: [] },
      responsibilities: ['Earn points', 'Redeem rewards', 'View tier status'],
    },
    {
      id: 'p-program-mgr',
      name: 'Program Manager',
      shortName: 'PgmMgr',
      description: 'Business stakeholder who configures tiers, campaigns, and reward catalogs',
      kind: 'person',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: [] },
      responsibilities: ['Configure tiers', 'Manage campaigns', 'Review analytics'],
    },
    {
      id: 'p-partner',
      name: 'Partner Merchant',
      shortName: 'Prtnr',
      description: 'External merchant offering co-branded rewards and point earning opportunities',
      kind: 'person',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: [] },
      responsibilities: ['Supply offers', 'Honor redemptions', 'Report transactions'],
    },
    {
      id: 't-points-earned',
      name: 'Points Earned',
      shortName: 'PtsEvt',
      description: 'Business event triggered when a member earns loyalty points from a transaction',
      kind: 'trigger',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },
    {
      id: 't-reward-redeemed',
      name: 'Reward Redeemed',
      shortName: 'RdmEvt',
      description: 'Business event triggered when a member redeems points for a reward',
      kind: 'trigger',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // BUSINESS viewpoint · component level  (evaluation)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'eval-engagement',
      name: 'Member Engagement Score',
      shortName: 'EngScr',
      description: 'Composite metric tracking member activity, redemption frequency, and program interaction',
      kind: 'evaluation',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['BigData'] },
      responsibilities: ['Aggregate activity signals', 'Compute engagement index'],
    },
    {
      id: 'eval-churn-biz',
      name: 'Churn Risk Assessment',
      shortName: 'ChrnBz',
      description: 'Business-level assessment of member churn probability based on behavioral trends',
      kind: 'evaluation',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['BigData', 'ML'] },
      responsibilities: ['Track inactivity trends', 'Flag at-risk members'],
    },

    // ════════════════════════════════════════════════════════════════
    // APPLICATION viewpoint · context level  (system, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 's-loyalty',
      name: 'Loyalty Platform',
      shortName: 'Loyal',
      description: 'Core loyalty management system handling points, tiers, rewards, and member profiles',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'GROW', size: 'XL', tags: ['REST', 'SOA'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Manage points', 'Process redemptions', 'Track tiers'],
    },
    {
      id: 's-partner-hub',
      name: 'Partner Integration Hub',
      shortName: 'PHub',
      description: 'Middleware connecting the loyalty platform with external partner merchant systems',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'GROW', size: 'L', tags: ['REST', 'EDI'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Transform partner data', 'Route transactions', 'SLA monitoring'],
    },
    {
      id: 's-notification',
      name: 'Notification Service',
      shortName: 'Notif',
      description: 'Sends loyalty-related emails, push notifications, and SMS to members',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'MATURE', size: 'S', tags: ['EDA', 'Stateless'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Send emails', 'Push notifications', 'SMS alerts'],
    },
    {
      id: 's-analytics',
      name: 'Analytics Platform',
      shortName: 'Anlyt',
      description: 'Loyalty analytics, reporting, and ML-driven insights for program optimization',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'INTRO', size: 'M', tags: ['BigData', 'ML'], deploymentStage: 'TESTING' },
      responsibilities: ['Generate reports', 'Train models', 'Member segmentation'],
    },
    {
      id: 't-tier-upgrade',
      name: 'Tier Upgrade Event',
      shortName: 'TierUp',
      description: 'Application event when a member crosses a tier threshold (Silver → Gold → Platinum)',
      kind: 'trigger',
      viewpoint: 'application',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // APPLICATION viewpoint · container level  (container, aimodel)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'c-member-portal',
      name: 'Member Portal',
      shortName: 'Portal',
      description: 'Web application where loyalty members view balances, browse rewards, and track tier progress',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-loyalty',
      metadata: { maturity: 'GROW', appType: 'WEB', tags: ['REST', 'Stateless'], technology: 'React / TypeScript', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Display member dashboard', 'Browse reward catalog', 'Tier progress UI'],
    },
    {
      id: 'c-points-engine',
      name: 'Points Engine',
      shortName: 'PtsEng',
      description: 'Microservice that calculates, accrues, and debits loyalty points for every transaction',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-loyalty',
      metadata: { maturity: 'GROW', appType: 'WEB', tags: ['REST', 'EDA', 'Java'], technology: 'Java / Spring Boot', deploymentStage: 'PRODUCTION', tps: 800 },
      responsibilities: ['Calculate earnings', 'Process debits', 'Maintain ledger'],
    },
    {
      id: 'c-rewards-catalog',
      name: 'Rewards Catalog Service',
      shortName: 'RwdCat',
      description: 'Manages the catalog of available rewards, partner offers, and redemption rules',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-loyalty',
      metadata: { maturity: 'GROW', appType: 'WEB', tags: ['REST', 'RDMS', 'Java'], technology: 'Java / Spring Boot', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Manage rewards', 'Enforce redemption rules', 'Partner offer sync'],
    },
    {
      id: 'c-campaign-mgr',
      name: 'Campaign Manager',
      shortName: 'CmpMgr',
      description: 'Configures and evaluates promotional campaigns such as double-points weekends',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-loyalty',
      metadata: { maturity: 'INTRO', appType: 'WEB', tags: ['REST', 'EDA'], technology: 'Node.js / Express', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Create campaigns', 'Evaluate eligibility', 'Track ROI'],
    },
    {
      id: 'c-member-db',
      name: 'Member Database',
      shortName: 'MbrDB',
      description: 'Relational store for member profiles, point balances, and transaction history',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-loyalty',
      metadata: { maturity: 'MATURE', tags: ['RDMS', 'PII'], technology: 'PostgreSQL', deploymentStage: 'PRODUCTION', pii: true },
      responsibilities: ['Store member profiles', 'Point balances', 'Transaction log'],
    },
    {
      id: 'c-offer-model',
      name: 'Offer Recommendation Model',
      shortName: 'OffrAI',
      description: 'ML model that generates personalized reward and offer recommendations for each member',
      kind: 'aimodel',
      viewpoint: 'application',
      parentId: 's-loyalty',
      metadata: { maturity: 'INTRO', tags: ['ML', 'Python'], technology: 'scikit-learn / FastAPI', deploymentStage: 'TESTING' },
      responsibilities: ['Personalized offers', 'Affinity scoring', 'Campaign targeting'],
    },

    // ════════════════════════════════════════════════════════════════
    // APPLICATION viewpoint · component level  (component, retriever, evaluation, artifact)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'comp-points-calc',
      name: 'Points Calculator',
      shortName: 'PtsCal',
      description: 'Calculates point earnings based on transaction amount, tier multiplier, and campaign bonuses',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-points-engine',
      metadata: { tags: ['Java'], technology: 'Spring' },
      responsibilities: ['Apply earning rules', 'Tier multipliers', 'Bonus calculation'],
    },
    {
      id: 'comp-tier-engine',
      name: 'Tier Engine',
      shortName: 'TierEn',
      description: 'Manages tier progression logic: evaluates qualifying activity and promotes/demotes members',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-points-engine',
      metadata: { tags: ['Java', 'EDA'], technology: 'Spring' },
      responsibilities: ['Evaluate tier thresholds', 'Promote/demote', 'Emit tier events'],
    },
    {
      id: 'comp-redemption-proc',
      name: 'Redemption Processor',
      shortName: 'RdmPrc',
      description: 'Handles reward redemption workflow: validates balance, debits points, fulfills reward',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-rewards-catalog',
      metadata: { tags: ['REST', 'Java'], technology: 'Spring MVC' },
      responsibilities: ['Validate balance', 'Debit points', 'Trigger fulfillment'],
    },
    {
      id: 'comp-campaign-rules',
      name: 'Campaign Rule Engine',
      shortName: 'CmpRul',
      description: 'Evaluates campaign eligibility rules, time windows, and member segment targeting',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-campaign-mgr',
      metadata: { tags: ['REST'], technology: 'Node.js' },
      responsibilities: ['Rule evaluation', 'Segment matching', 'Time-window checks'],
    },
    {
      id: 'ret-offer-search',
      name: 'Offer Search',
      shortName: 'OffrSr',
      description: 'Semantic search across reward catalog using embeddings for natural-language queries',
      kind: 'retriever',
      viewpoint: 'application',
      parentId: 'c-rewards-catalog',
      metadata: { tags: ['ML'], technology: 'Elasticsearch' },
      responsibilities: ['Full-text search', 'Fuzzy matching', 'Relevance ranking'],
    },
    {
      id: 'eval-rec-accuracy',
      name: 'Recommendation Accuracy',
      shortName: 'RecAcc',
      description: 'Evaluates precision and recall of the offer recommendation model against redemption data',
      kind: 'evaluation',
      viewpoint: 'application',
      parentId: 'c-rewards-catalog',
      metadata: { tags: ['ML'] },
      responsibilities: ['Precision/recall metrics', 'A/B test analysis', 'Model drift detection'],
    },
    {
      id: 'a-loyalty-api',
      name: 'Loyalty API Spec',
      shortName: 'LoyAPI',
      description: 'OpenAPI specification for the Points Engine REST endpoints',
      kind: 'artifact',
      viewpoint: 'application',
      parentId: 'c-points-engine',
      metadata: { tags: ['REST'] },
      responsibilities: [],
    },
    {
      id: 'a-reward-schema',
      name: 'Reward Data Schema',
      shortName: 'RwdSch',
      description: 'Entity-relationship diagram for the rewards catalog domain',
      kind: 'artifact',
      viewpoint: 'application',
      parentId: 'c-rewards-catalog',
      metadata: { tags: ['RDMS'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // TECHNICAL viewpoint · container level  (container, aimodel, vectorstore)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'tc-postgres',
      name: 'PostgreSQL Cluster',
      shortName: 'PgSQL',
      description: 'Primary relational database cluster with read replicas for member and points data',
      kind: 'container',
      viewpoint: 'technology',
      parentId: 's-loyalty',
      metadata: { maturity: 'MATURE', tags: ['RDMS', 'PII'], technology: 'PostgreSQL 16', deploymentStage: 'PRODUCTION', pii: true },
      responsibilities: ['Primary storage', 'Read replicas', 'Point-in-time recovery'],
    },
    {
      id: 'tc-redis',
      name: 'Redis Cache',
      shortName: 'Redis',
      description: 'In-memory cache for session tokens, point balance snapshots, and rate limiting',
      kind: 'container',
      viewpoint: 'technology',
      parentId: 's-loyalty',
      metadata: { maturity: 'MATURE', tags: ['NoSQL'], technology: 'Redis 7', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Session caching', 'Balance snapshots', 'Rate limit counters'],
    },
    {
      id: 'tc-kafka',
      name: 'Kafka Cluster',
      shortName: 'Kafka',
      description: 'Event streaming backbone for points-earned, tier-upgrade, and redemption events',
      kind: 'container',
      viewpoint: 'technology',
      parentId: 's-loyalty',
      metadata: { maturity: 'MATURE', tags: ['EDA'], technology: 'Apache Kafka 3.7', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Event streaming', 'Topic management', 'Consumer groups'],
    },
    {
      id: 'tc-k8s',
      name: 'Kubernetes Cluster',
      shortName: 'K8s',
      description: 'Container orchestration platform running all loyalty microservices',
      kind: 'container',
      viewpoint: 'technology',
      parentId: 's-loyalty',
      metadata: { maturity: 'GROW', tags: ['SOA'], technology: 'Kubernetes 1.30', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Service orchestration', 'Auto-scaling', 'Health checks'],
    },
    {
      id: 'tc-churn-model',
      name: 'Churn Prediction Model',
      shortName: 'ChrnAI',
      description: 'ML model predicting member churn probability from behavioral features',
      kind: 'aimodel',
      viewpoint: 'technology',
      parentId: 's-analytics',
      metadata: { maturity: 'INTRO', tags: ['ML', 'Python'], technology: 'XGBoost / MLflow', deploymentStage: 'TESTING' },
      responsibilities: ['Feature extraction', 'Churn scoring', 'Model retraining'],
    },
    {
      id: 'tc-offer-vectors',
      name: 'Offer Embeddings',
      shortName: 'OffrVec',
      description: 'Vector database storing reward/offer embeddings for similarity-based recommendations',
      kind: 'vectorstore',
      viewpoint: 'technology',
      parentId: 's-analytics',
      metadata: { maturity: 'INTRO', tags: ['ML'], technology: 'Pinecone', deploymentStage: 'TESTING' },
      responsibilities: ['Store offer vectors', 'Nearest-neighbor search', 'Index management'],
    },
    {
      id: 'tc-member-vectors',
      name: 'Member Behavior Vectors',
      shortName: 'MbrVec',
      description: 'Vector database encoding member behavioral patterns for segmentation and personalization',
      kind: 'vectorstore',
      viewpoint: 'technology',
      parentId: 's-analytics',
      metadata: { maturity: 'INTRO', tags: ['ML', 'PII'], technology: 'Weaviate', deploymentStage: 'TESTING', pii: true },
      responsibilities: ['Store behavior vectors', 'Segment similarity', 'Privacy controls'],
    },
    {
      id: 't-deploy-event',
      name: 'Deployment Triggered',
      shortName: 'Deploy',
      description: 'CI/CD pipeline triggers a rolling container deployment',
      kind: 'trigger',
      viewpoint: 'technology',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },
    {
      id: 't-scale-event',
      name: 'Auto-Scale Event',
      shortName: 'Scale',
      description: 'HPA triggers pod scaling based on CPU/memory thresholds',
      kind: 'trigger',
      viewpoint: 'technology',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // TECHNICAL viewpoint · component level  (component, retriever, artifact)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'tcomp-kafka-consumer',
      name: 'Loyalty Event Consumer',
      shortName: 'KfkCon',
      description: 'Consumes points-earned and tier-upgrade events from Kafka topics',
      kind: 'component',
      viewpoint: 'technology',
      parentId: 'tc-kafka',
      metadata: { tags: ['EDA', 'Java'], technology: 'Spring Kafka' },
      responsibilities: ['Consume messages', 'Offset management', 'Dead-letter handling'],
    },
    {
      id: 'tcomp-cache-mgr',
      name: 'Cache Manager',
      shortName: 'CchMgr',
      description: 'Manages cache invalidation and TTL policies for balance snapshots',
      kind: 'component',
      viewpoint: 'technology',
      parentId: 'tc-redis',
      metadata: { tags: ['NoSQL', 'Java'], technology: 'Lettuce / Spring Cache' },
      responsibilities: ['Cache invalidation', 'TTL policies', 'Write-through pattern'],
    },
    {
      id: 'tcomp-ingress',
      name: 'Ingress Controller',
      shortName: 'Ingres',
      description: 'API gateway and TLS termination handling external traffic routing',
      kind: 'component',
      viewpoint: 'technology',
      parentId: 'tc-k8s',
      metadata: { tags: ['REST', 'SOA'], technology: 'NGINX Ingress' },
      responsibilities: ['TLS termination', 'Path routing', 'Rate limiting'],
    },
    {
      id: 'tret-offer-retriever',
      name: 'Offer Retriever',
      shortName: 'OffrRt',
      description: 'Queries offer embeddings from Pinecone for similarity-based recommendation serving',
      kind: 'retriever',
      viewpoint: 'technology',
      parentId: 'tc-churn-model',
      metadata: { tags: ['ML', 'Python'], technology: 'LangChain / Pinecone Client' },
      responsibilities: ['Embedding lookup', 'Similarity threshold', 'Result ranking'],
    },
    {
      id: 'tret-behavior-retriever',
      name: 'Behavior Pattern Retriever',
      shortName: 'BhvRet',
      description: 'Queries member behavior vectors from Weaviate for cohort analysis',
      kind: 'retriever',
      viewpoint: 'technology',
      parentId: 'tc-churn-model',
      metadata: { tags: ['ML', 'Python'], technology: 'Weaviate Client' },
      responsibilities: ['Segment matching', 'Cohort analysis', 'Personalization signals'],
    },
    {
      id: 'ta-helm-charts',
      name: 'Helm Charts',
      shortName: 'Helm',
      description: 'Kubernetes deployment manifests and Helm chart templates for all loyalty services',
      kind: 'artifact',
      viewpoint: 'technology',
      parentId: 'tc-k8s',
      metadata: { tags: ['SOA'] },
      responsibilities: [],
    },
    {
      id: 'ta-ci-pipeline',
      name: 'CI/CD Pipeline',
      shortName: 'CI',
      description: 'GitHub Actions workflow for build, test, and deploy of the loyalty platform',
      kind: 'artifact',
      viewpoint: 'technology',
      parentId: 'tc-k8s',
      metadata: { tags: ['SOA'] },
      responsibilities: [],
    },
  ],
  relationships: [
    // ── Cross-viewpoint: Business persons → Application systems ──
    { id: 'r1', sourceId: 'p-member', targetId: 's-loyalty', type: 'sync', label: 'Earns & redeems points', protocol: 'HTTPS' },
    { id: 'r2', sourceId: 'p-program-mgr', targetId: 's-loyalty', type: 'sync', label: 'Configures program', protocol: 'HTTPS' },
    { id: 'r3', sourceId: 'p-partner', targetId: 's-partner-hub', type: 'sync', label: 'Supplies offers & transactions', protocol: 'HTTPS' },
    { id: 'r4', sourceId: 'p-program-mgr', targetId: 's-analytics', type: 'sync', label: 'Reviews reports', protocol: 'HTTPS' },

    // ── Business triggers → Application systems ──
    { id: 'r5', sourceId: 't-points-earned', targetId: 's-notification', type: 'trigger', label: 'Triggers balance notification' },
    { id: 'r6', sourceId: 't-points-earned', targetId: 's-analytics', type: 'trigger', label: 'Triggers analytics ingestion' },
    { id: 'r7', sourceId: 't-reward-redeemed', targetId: 's-notification', type: 'trigger', label: 'Triggers redemption confirmation' },

    // ── Application · Context (system-to-system) ──
    { id: 'r10', sourceId: 's-loyalty', targetId: 's-partner-hub', type: 'sync', label: 'Syncs partner offers', protocol: 'HTTPS/REST' },
    { id: 'r11', sourceId: 's-loyalty', targetId: 's-notification', type: 'async', label: 'Sends member notifications', protocol: 'AMQP' },
    { id: 'r12', sourceId: 's-loyalty', targetId: 's-analytics', type: 'dataflow', label: 'Streams loyalty events', protocol: 'Kafka' },
    { id: 'r13', sourceId: 't-tier-upgrade', targetId: 's-notification', type: 'trigger', label: 'Triggers tier-up congratulations' },
    { id: 'r14', sourceId: 's-partner-hub', targetId: 's-analytics', type: 'dataflow', label: 'Partner transaction feed', protocol: 'Kafka' },

    // ── Application · Container ──
    { id: 'r20', sourceId: 'c-member-portal', targetId: 'c-points-engine', type: 'sync', label: 'Fetches balance & history', protocol: 'HTTPS' },
    { id: 'r21', sourceId: 'c-member-portal', targetId: 'c-rewards-catalog', type: 'sync', label: 'Browses rewards', protocol: 'HTTPS' },
    { id: 'r22', sourceId: 'c-points-engine', targetId: 'c-member-db', type: 'dataflow', label: 'Reads/writes balances' },
    { id: 'r23', sourceId: 'c-rewards-catalog', targetId: 'c-member-db', type: 'dataflow', label: 'Reads member tier for eligibility' },
    { id: 'r24', sourceId: 'c-campaign-mgr', targetId: 'c-points-engine', type: 'sync', label: 'Applies bonus multipliers' },
    { id: 'r25', sourceId: 'c-offer-model', targetId: 'c-rewards-catalog', type: 'sync', label: 'Provides personalized rankings' },
    { id: 'r26', sourceId: 'c-points-engine', targetId: 'c-offer-model', type: 'queries_model', label: 'Queries offer affinity' },
    { id: 'r27', sourceId: 'c-campaign-mgr', targetId: 'c-rewards-catalog', type: 'sync', label: 'Publishes promotional offers' },

    // ── Application · Component ──
    { id: 'r30', sourceId: 'comp-points-calc', targetId: 'comp-tier-engine', type: 'sync', label: 'Forwards qualifying activity' },
    { id: 'r31', sourceId: 'comp-tier-engine', targetId: 'c-member-db', type: 'dataflow', label: 'Updates tier status' },
    { id: 'r32', sourceId: 'comp-redemption-proc', targetId: 'c-member-db', type: 'dataflow', label: 'Debits points' },
    { id: 'r33', sourceId: 'comp-campaign-rules', targetId: 'comp-points-calc', type: 'sync', label: 'Applies bonus rules' },
    { id: 'r34', sourceId: 'ret-offer-search', targetId: 'comp-redemption-proc', type: 'retrieves', label: 'Searches relevant offers' },
    { id: 'r35', sourceId: 'eval-rec-accuracy', targetId: 'comp-redemption-proc', type: 'evaluates', label: 'Measures recommendation hit rate' },
    { id: 'r36', sourceId: 'comp-points-calc', targetId: 'a-loyalty-api', type: 'dependency', label: 'Implements spec' },
    { id: 'r37', sourceId: 'comp-redemption-proc', targetId: 'a-reward-schema', type: 'dependency', label: 'Conforms to schema' },

    // ── Technical · Container ──
    { id: 'r40', sourceId: 'tc-kafka', targetId: 'tc-k8s', type: 'dependency', label: 'Deployed on' },
    { id: 'r41', sourceId: 'tc-redis', targetId: 'tc-k8s', type: 'dependency', label: 'Deployed on' },
    { id: 'r42', sourceId: 'tc-postgres', targetId: 'tc-k8s', type: 'dependency', label: 'Deployed on' },
    { id: 'r43', sourceId: 'tc-churn-model', targetId: 'tc-offer-vectors', type: 'retrieves_from', label: 'Queries offer embeddings' },
    { id: 'r44', sourceId: 'tc-churn-model', targetId: 'tc-member-vectors', type: 'retrieves_from', label: 'Queries behavior patterns' },
    { id: 'r45', sourceId: 't-deploy-event', targetId: 'tc-k8s', type: 'trigger', label: 'Triggers rolling update' },
    { id: 'r46', sourceId: 't-scale-event', targetId: 'tc-k8s', type: 'trigger', label: 'Triggers HPA scaling' },

    // ── Technical · Component ──
    { id: 'r50', sourceId: 'tcomp-kafka-consumer', targetId: 'tcomp-cache-mgr', type: 'async', label: 'Invalidates balance cache' },
    { id: 'r51', sourceId: 'tret-offer-retriever', targetId: 'tc-offer-vectors', type: 'retrieves_from', label: 'Vector similarity query' },
    { id: 'r52', sourceId: 'tret-behavior-retriever', targetId: 'tc-member-vectors', type: 'retrieves_from', label: 'Segment lookup' },
    { id: 'r53', sourceId: 'tcomp-ingress', targetId: 'tc-kafka', type: 'async', label: 'Routes async events' },
    { id: 'r54', sourceId: 'ta-ci-pipeline', targetId: 'ta-helm-charts', type: 'dependency', label: 'Deploys via Helm' },
  ],
  positions: [],
  views: [
    {
      id: 'v-biz-context',
      name: 'Business Overview',
      zoomLevel: 'context',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-biz-component',
      name: 'Business KPIs',
      zoomLevel: 'component',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-app-context',
      name: 'Application Landscape',
      zoomLevel: 'context',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-app-container',
      name: 'Loyalty Architecture',
      zoomLevel: 'container',
      focusEntityId: 's-loyalty',
      filters: {},
    },
    {
      id: 'v-app-component',
      name: 'Points Engine Internals',
      zoomLevel: 'component',
      focusEntityId: 'c-points-engine',
      filters: {},
    },
    {
      id: 'v-tech-container',
      name: 'Infrastructure Overview',
      zoomLevel: 'container',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-tech-component',
      name: 'Technical Internals',
      zoomLevel: 'component',
      focusEntityId: null,
      filters: {},
    },
  ],
  notes: [],
  boundaries: [],
};
