import type { ArchLensProject } from '../domain/types';

export const EXAMPLE_PROJECT: ArchLensProject = {
  version: '1.0.0',
  name: 'Loyalty Rewards Platform',
  description: 'Enterprise loyalty programme — points, tiers, personalised offers, AI-driven engagement, and ArchiMate coverage across Business, Application, and Technology viewpoints.',
  createdAt: '2026-06-01T00:00:00.000Z',
  updatedAt: '2026-06-01T00:00:00.000Z',
  entities: [
    // ════════════════════════════════════════════════════════════════
    // BUSINESS VIEWPOINT
    // ════════════════════════════════════════════════════════════════
    {
      id: 'p-member',
      identificationId: 'BIZ-001',
      name: 'Loyalty Member',
      shortName: 'Mbr',
      description: 'End user enrolled in the loyalty program who earns and redeems points',
      kind: 'person',
      viewpoint: 'business',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Sarah Chen', organization: 'Product & Strategy', sme: 'Laura Kim', tags: [] },
      responsibilities: ['Earn points', 'Redeem rewards', 'View tier status'],
    },
    {
      id: 'p-manager',
      name: 'Program Manager',
      shortName: 'PgmMgr',
      description: 'Business stakeholder who configures tiers, campaigns, and reward catalogs',
      kind: 'person',
      viewpoint: 'business',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Sarah Chen', organization: 'Product & Strategy', sme: 'Laura Kim', tags: [] },
      responsibilities: ['Configure tiers', 'Manage campaigns', 'Review analytics'],
    },
    {
      id: 't-points-earned',
      name: 'Points Earned',
      shortName: 'PtsEvt',
      description: 'Business event triggered when a member earns loyalty points from a transaction',
      kind: 'trigger',
      viewpoint: 'business',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'James Patel', organization: 'Loyalty Core Squad', sme: 'Marco Rossi', tags: ['EDA'] },
      responsibilities: [],
    },
    {
      id: 't-reward-redeemed',
      name: 'Reward Redeemed',
      shortName: 'RdmEvt',
      description: 'Business event triggered when a member redeems points for a reward',
      kind: 'trigger',
      viewpoint: 'business',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Chris Anderson', organization: 'Rewards & Catalog Squad', sme: 'Anna Schmidt', tags: ['EDA'] },
      responsibilities: [],
    },
    {
      id: 'eval-engagement',
      name: 'Member Engagement Score',
      shortName: 'EngScr',
      description: 'Metric tracking member activity, redemption frequency, and program interaction',
      kind: 'evaluation',
      viewpoint: 'business',
      zoomLevel: 'component',
      parentId: null,
      metadata: { owner: 'Aisha Johnson', organization: 'Data & Analytics Squad', sme: 'Yuki Tanaka', tags: ['BigData'] },
      responsibilities: ['Aggregate activity signals', 'Compute engagement index'],
    },

    // ════════════════════════════════════════════════════════════════
    // APPLICATION VIEWPOINT
    // ════════════════════════════════════════════════════════════════
    // Context level — systems
    {
      id: 's-loyalty',
      name: 'Loyalty Platform',
      shortName: 'Loyal',
      description: 'Core loyalty management system handling points, tiers, rewards, and member profiles',
      kind: 'system',
      viewpoint: 'application',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'James Patel', organization: 'Loyalty Core Squad', sme: 'Marco Rossi', maturity: 'GROW', size: 'XL', tags: ['REST', 'SOA'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Manage points', 'Process redemptions', 'Track tiers'],
    },
    {
      id: 's-notification',
      name: 'Notification Service',
      shortName: 'Notif',
      description: 'Sends loyalty-related emails, push notifications, and SMS to members',
      kind: 'system',
      viewpoint: 'application',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Ben Wilson', organization: 'Platform Engineering', sme: 'Diego Martinez', maturity: 'MATURE', size: 'S', tags: ['EDA', 'Stateless'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Send emails', 'Push notifications', 'SMS alerts'],
    },
    {
      id: 's-analytics',
      name: 'Analytics Platform',
      shortName: 'Anlyt',
      description: 'Loyalty analytics, reporting, and ML-driven insights for program optimization',
      kind: 'system',
      viewpoint: 'application',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Aisha Johnson', organization: 'Data & Analytics Squad', sme: 'Yuki Tanaka', maturity: 'INTRO', size: 'M', tags: ['BigData', 'ML'], deploymentStage: 'TESTING' },
      responsibilities: ['Generate reports', 'Train models', 'Member segmentation'],
    },
    // Container level — inside s-loyalty
    {
      id: 'c-portal',
      name: 'Member Portal',
      shortName: 'Portal',
      description: 'Web app where loyalty members view balances, browse rewards, and track tier progress',
      kind: 'container',
      viewpoint: 'application',
      zoomLevel: 'container',
      parentId: 's-loyalty',
      metadata: { owner: 'Emily Torres', organization: 'Member Experience Squad', sme: 'David Nguyen', maturity: 'GROW', appType: 'WEB', tags: ['REST', 'Stateless'], technology: 'React / TypeScript', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Display member dashboard', 'Browse reward catalog', 'Tier progress UI'],
    },
    {
      id: 'c-points-engine',
      name: 'Points Engine',
      shortName: 'PtsEng',
      description: 'Microservice that calculates, accrues, and debits loyalty points',
      kind: 'container',
      viewpoint: 'application',
      zoomLevel: 'container',
      parentId: 's-loyalty',
      metadata: { owner: 'James Patel', organization: 'Loyalty Core Squad', sme: 'Marco Rossi', maturity: 'GROW', appType: 'WEB', tags: ['REST', 'EDA', 'Java'], technology: 'Java / Spring Boot', deploymentStage: 'PRODUCTION', tps: 800 },
      responsibilities: ['Calculate earnings', 'Process debits', 'Maintain ledger'],
    },
    {
      id: 'c-rewards',
      name: 'Rewards Catalog',
      shortName: 'RwdCat',
      description: 'Manages the catalog of available rewards, partner offers, and redemption rules',
      kind: 'container',
      viewpoint: 'application',
      zoomLevel: 'container',
      parentId: 's-loyalty',
      metadata: { owner: 'Chris Anderson', organization: 'Rewards & Catalog Squad', sme: 'Anna Schmidt', maturity: 'GROW', appType: 'WEB', tags: ['REST', 'RDMS', 'Java'], technology: 'Java / Spring Boot', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Manage rewards', 'Enforce redemption rules', 'Partner offer sync'],
    },
    {
      id: 'c-member-db',
      name: 'Member Database',
      shortName: 'MbrDB',
      description: 'Relational store for member profiles, point balances, and transaction history',
      kind: 'container',
      viewpoint: 'application',
      zoomLevel: 'container',
      parentId: 's-loyalty',
      metadata: { owner: 'Ben Wilson', organization: 'Platform Engineering', sme: 'Diego Martinez', maturity: 'MATURE', tags: ['RDMS', 'PII'], technology: 'PostgreSQL', deploymentStage: 'PRODUCTION', pii: true },
      responsibilities: ['Store member profiles', 'Point balances', 'Transaction log'],
    },
    // Component level — inside c-points-engine
    {
      id: 'comp-calculator',
      name: 'Points Calculator',
      shortName: 'PtsCal',
      description: 'Calculates point earnings based on transaction amount, tier multiplier, and bonuses',
      kind: 'component',
      viewpoint: 'application',
      zoomLevel: 'component',
      parentId: 'c-points-engine',
      metadata: { owner: 'James Patel', organization: 'Loyalty Core Squad', sme: 'Marco Rossi', tags: ['Java'], technology: 'Spring' },
      responsibilities: ['Apply earning rules', 'Tier multipliers', 'Bonus calculation'],
    },
    {
      id: 'comp-tier-engine',
      name: 'Tier Engine',
      shortName: 'TierEn',
      description: 'Evaluates qualifying activity and promotes/demotes members across tiers',
      kind: 'component',
      viewpoint: 'application',
      zoomLevel: 'component',
      parentId: 'c-points-engine',
      metadata: { owner: 'James Patel', organization: 'Loyalty Core Squad', sme: 'Marco Rossi', tags: ['Java', 'EDA'], technology: 'Spring' },
      responsibilities: ['Evaluate tier thresholds', 'Promote/demote', 'Emit tier events'],
    },

    // ════════════════════════════════════════════════════════════════
    // TECHNOLOGY VIEWPOINT
    // ════════════════════════════════════════════════════════════════
    // Context level — technology systems (own containment hierarchy)
    {
      id: 's-infra',
      name: 'Cloud Infrastructure',
      shortName: 'Infra',
      description: 'Core cloud platform hosting all loyalty microservices and data stores',
      kind: 'system',
      viewpoint: 'technology',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Ben Wilson', organization: 'Platform Engineering', sme: 'Diego Martinez', maturity: 'MATURE', size: 'XL', tags: ['SOA'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Container orchestration', 'Database hosting', 'Event streaming'],
    },
    {
      id: 's-ml-platform',
      name: 'ML Platform',
      shortName: 'MLPlat',
      description: 'Machine-learning infrastructure for training and serving loyalty models',
      kind: 'system',
      viewpoint: 'technology',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Aisha Johnson', organization: 'Data & Analytics Squad', sme: 'Yuki Tanaka', maturity: 'INTRO', size: 'M', tags: ['ML', 'Python'], deploymentStage: 'TESTING' },
      responsibilities: ['Model training', 'Feature store', 'Serving infrastructure'],
    },
    // Container level — inside s-infra
    {
      id: 'tc-k8s',
      name: 'Kubernetes Cluster',
      shortName: 'K8s',
      description: 'Container orchestration platform running all loyalty microservices',
      kind: 'container',
      viewpoint: 'technology',
      zoomLevel: 'container',
      parentId: 's-infra',
      metadata: { owner: 'Ben Wilson', organization: 'Platform Engineering', sme: 'Diego Martinez', maturity: 'GROW', tags: ['SOA'], technology: 'Kubernetes 1.30', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Service orchestration', 'Auto-scaling', 'Health checks'],
    },
    {
      id: 'tc-postgres',
      name: 'PostgreSQL Cluster',
      shortName: 'PgSQL',
      description: 'Primary relational database cluster with read replicas',
      kind: 'container',
      viewpoint: 'technology',
      zoomLevel: 'container',
      parentId: 's-infra',
      metadata: { owner: 'Ben Wilson', organization: 'Platform Engineering', sme: 'Diego Martinez', maturity: 'MATURE', tags: ['RDMS', 'PII'], technology: 'PostgreSQL 16', deploymentStage: 'PRODUCTION', pii: true },
      responsibilities: ['Primary storage', 'Read replicas', 'Point-in-time recovery'],
    },
    {
      id: 'tc-kafka',
      name: 'Kafka Cluster',
      shortName: 'Kafka',
      description: 'Event streaming backbone for loyalty domain events',
      kind: 'container',
      viewpoint: 'technology',
      zoomLevel: 'container',
      parentId: 's-infra',
      metadata: { owner: 'Ben Wilson', organization: 'Platform Engineering', sme: 'Diego Martinez', maturity: 'MATURE', tags: ['EDA'], technology: 'Apache Kafka 3.7', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Event streaming', 'Topic management', 'Consumer groups'],
    },
    // Container level — inside s-ml-platform
    {
      id: 'tc-churn-model',
      name: 'Churn Prediction Model',
      shortName: 'ChrnAI',
      description: 'ML model predicting member churn probability from behavioral features',
      kind: 'aimodel',
      viewpoint: 'technology',
      zoomLevel: 'container',
      parentId: 's-ml-platform',
      metadata: { owner: 'Aisha Johnson', organization: 'Data & Analytics Squad', sme: 'Yuki Tanaka', maturity: 'INTRO', tags: ['ML', 'Python'], technology: 'XGBoost / MLflow', deploymentStage: 'TESTING' },
      responsibilities: ['Feature extraction', 'Churn scoring', 'Model retraining'],
    },
    {
      id: 'tc-offer-vectors',
      name: 'Offer Embeddings',
      shortName: 'OffrVec',
      description: 'Vector database storing reward/offer embeddings for recommendations',
      kind: 'vectorstore',
      viewpoint: 'technology',
      zoomLevel: 'container',
      parentId: 's-ml-platform',
      metadata: { owner: 'Aisha Johnson', organization: 'Data & Analytics Squad', sme: 'Yuki Tanaka', maturity: 'INTRO', tags: ['ML'], technology: 'Pinecone', deploymentStage: 'TESTING' },
      responsibilities: ['Store offer vectors', 'Nearest-neighbor search', 'Index management'],
    },
    // Triggers
    {
      id: 't-deploy-event',
      name: 'Deployment Triggered',
      shortName: 'Deploy',
      description: 'CI/CD pipeline triggers a rolling container deployment',
      kind: 'trigger',
      viewpoint: 'technology',
      zoomLevel: 'context',
      parentId: null,
      metadata: { owner: 'Ben Wilson', organization: 'Platform Engineering', sme: 'Diego Martinez', tags: ['EDA'] },
      responsibilities: [],
    },
  ],
  relationships: [
    // ── Business → Application (cross-viewpoint) ──
    { id: 'r1', sourceId: 'p-member', targetId: 's-loyalty', type: 'sync', label: 'Earns & redeems points', protocol: 'HTTPS' },
    { id: 'r2', sourceId: 'p-manager', targetId: 's-loyalty', type: 'sync', label: 'Configures program', protocol: 'HTTPS' },
    { id: 'r3', sourceId: 'p-manager', targetId: 's-analytics', type: 'sync', label: 'Reviews reports', protocol: 'HTTPS' },
    { id: 'r4', sourceId: 't-points-earned', targetId: 's-notification', type: 'trigger', label: 'Triggers balance notification' },
    { id: 'r5', sourceId: 't-reward-redeemed', targetId: 's-notification', type: 'trigger', label: 'Triggers redemption confirmation' },
    { id: 'r6', sourceId: 'eval-engagement', targetId: 's-analytics', type: 'dataflow', label: 'Feeds engagement metrics' },

    // ── Application context (system-to-system) ──
    { id: 'r10', sourceId: 's-loyalty', targetId: 's-notification', type: 'async', label: 'Sends member notifications', protocol: 'AMQP' },
    { id: 'r11', sourceId: 's-loyalty', targetId: 's-analytics', type: 'dataflow', label: 'Streams loyalty events', protocol: 'Kafka' },

    // ── Application container ──
    { id: 'r20', sourceId: 'c-portal', targetId: 'c-points-engine', type: 'sync', label: 'Fetches balance & history', protocol: 'HTTPS' },
    { id: 'r21', sourceId: 'c-portal', targetId: 'c-rewards', type: 'sync', label: 'Browses rewards', protocol: 'HTTPS' },
    { id: 'r22', sourceId: 'c-points-engine', targetId: 'c-member-db', type: 'dataflow', label: 'Reads/writes balances' },
    { id: 'r23', sourceId: 'c-rewards', targetId: 'c-member-db', type: 'dataflow', label: 'Reads member tier for eligibility' },

    // ── Application component ──
    { id: 'r30', sourceId: 'comp-calculator', targetId: 'comp-tier-engine', type: 'sync', label: 'Forwards qualifying activity' },
    { id: 'r31', sourceId: 'comp-tier-engine', targetId: 'c-member-db', type: 'dataflow', label: 'Updates tier status' },

    // ── Technology container ──
    { id: 'r40', sourceId: 'tc-kafka', targetId: 'tc-k8s', type: 'dependency', label: 'Deployed on' },
    { id: 'r41', sourceId: 'tc-postgres', targetId: 'tc-k8s', type: 'dependency', label: 'Deployed on' },
    { id: 'r42', sourceId: 'tc-churn-model', targetId: 'tc-offer-vectors', type: 'retrieves_from', label: 'Queries offer embeddings' },
    { id: 'r43', sourceId: 't-deploy-event', targetId: 'tc-k8s', type: 'trigger', label: 'Triggers rolling update' },

    // ── Application → Technology (cross-viewpoint) ──
    { id: 'r50', sourceId: 's-loyalty', targetId: 's-infra', type: 'dependency', label: 'Runs on cloud infrastructure' },
    { id: 'r51', sourceId: 's-analytics', targetId: 's-ml-platform', type: 'dependency', label: 'Uses ML platform' },
  ],
  positions: [],
  views: [
    { id: 'v-biz-context', name: 'Business Overview', zoomLevel: 'context', focusEntityId: null, filters: {} },
    { id: 'v-app-context', name: 'Application Landscape', zoomLevel: 'context', focusEntityId: null, filters: {} },
    { id: 'v-app-container', name: 'Loyalty Architecture', zoomLevel: 'container', focusEntityId: 's-loyalty', filters: {} },
    { id: 'v-tech-container', name: 'Infrastructure Overview', zoomLevel: 'container', focusEntityId: null, filters: {} },
  ],
  notes: [],
  boundaries: [],
};
