import type { ArchLensProject } from '../domain/types';

export const EXAMPLE_PROJECT: ArchLensProject = {
  version: '1.0.0',
  name: 'E-Commerce Platform',
  description: 'A modern e-commerce platform with microservices architecture and AI-powered recommendations',
  createdAt: '2026-03-27T00:00:00.000Z',
  updatedAt: '2026-03-27T00:00:00.000Z',
  entities: [
    // ════════════════════════════════════════════════════════════════
    // BUSINESS viewpoint · context level  (person, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'p-customer',
      name: 'Customer',
      shortName: 'Cust',
      description: 'End user shopping on the platform',
      kind: 'person',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: [] },
      responsibilities: ['Browse products', 'Place orders', 'Manage account'],
    },
    {
      id: 'p-admin',
      name: 'Admin',
      shortName: 'Adm',
      description: 'Internal administrator managing the platform',
      kind: 'person',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: [] },
      responsibilities: ['Manage products', 'Review orders', 'Configure platform'],
    },
    {
      id: 'p-support',
      name: 'Support Agent',
      shortName: 'Supp',
      description: 'Customer support representative',
      kind: 'person',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: [] },
      responsibilities: ['Handle customer inquiries', 'Process refunds', 'Escalate issues'],
    },
    {
      id: 't-order-event',
      name: 'Order Placed',
      shortName: 'OrdEvt',
      description: 'Event triggered when a customer completes checkout',
      kind: 'trigger',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },
    {
      id: 't-refund-request',
      name: 'Refund Requested',
      shortName: 'RefReq',
      description: 'Business event when a customer requests a refund',
      kind: 'trigger',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // BUSINESS viewpoint · component level  (evaluation, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'eval-csat',
      name: 'Customer Satisfaction Score',
      shortName: 'CSAT',
      description: 'Tracks customer satisfaction through post-purchase surveys',
      kind: 'evaluation',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['BigData'] },
      responsibilities: ['Aggregate survey results', 'Track NPS trends'],
    },
    {
      id: 'eval-conversion',
      name: 'Conversion Rate Monitor',
      shortName: 'CvtMon',
      description: 'Measures checkout funnel conversion rates',
      kind: 'evaluation',
      viewpoint: 'business',
      parentId: null,
      metadata: { tags: ['BigData'] },
      responsibilities: ['Track funnel drop-off', 'A/B test outcomes'],
    },

    // ════════════════════════════════════════════════════════════════
    // APPLICATION viewpoint · context level  (system, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 's-ecommerce',
      name: 'E-Commerce Platform',
      shortName: 'EComm',
      description: 'The main e-commerce system serving customer-facing features',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'GROW', size: 'XL', tags: ['REST', 'SOA'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Serve storefront', 'Process orders', 'Manage catalog'],
    },
    {
      id: 's-payment',
      name: 'Payment Gateway',
      shortName: 'PayGW',
      description: 'Third-party payment processing system',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'MATURE', size: 'L', tags: ['REST', 'PII'], deploymentStage: 'PRODUCTION', pii: true, pciDss: true },
      responsibilities: ['Process payments', 'Handle refunds', 'Fraud detection'],
    },
    {
      id: 's-analytics',
      name: 'Analytics Engine',
      shortName: 'Anlyt',
      description: 'Business analytics and reporting platform',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'INTRO', size: 'M', tags: ['BigData', 'ML'], deploymentStage: 'TESTING' },
      responsibilities: ['Aggregate events', 'Generate reports', 'ML predictions'],
    },
    {
      id: 's-notification',
      name: 'Notification Service',
      shortName: 'Notif',
      description: 'Sends emails, SMS, and push notifications',
      kind: 'system',
      viewpoint: 'application',
      parentId: null,
      metadata: { maturity: 'MATURE', size: 'S', tags: ['EDA', 'Stateless'], deploymentStage: 'PRODUCTION' },
      responsibilities: ['Send emails', 'Send SMS', 'Push notifications'],
    },
    {
      id: 't-price-change',
      name: 'Price Updated',
      shortName: 'PrcUpd',
      description: 'Application event when product pricing changes',
      kind: 'trigger',
      viewpoint: 'application',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // APPLICATION viewpoint · container level  (container, aimodel, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'c-web-app',
      name: 'Web Application',
      shortName: 'WebApp',
      description: 'React SPA serving the storefront',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-ecommerce',
      metadata: { maturity: 'GROW', appType: 'WEB', tags: ['REST', 'Stateless'], technology: 'React / TypeScript', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Render storefront UI', 'Handle user interactions'],
    },
    {
      id: 'c-api-gateway',
      name: 'API Gateway',
      shortName: 'APIGW',
      description: 'Entry point for all API calls, handles auth and routing',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-ecommerce',
      metadata: { maturity: 'GROW', appType: 'WEB', tags: ['REST', 'SOA'], technology: 'Node.js / Express', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Route requests', 'Authenticate users', 'Rate limiting'],
    },
    {
      id: 'c-order-service',
      name: 'Order Service',
      shortName: 'OrdSvc',
      description: 'Manages order lifecycle: creation, status, fulfillment',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-ecommerce',
      metadata: { maturity: 'GROW', appType: 'WEB', tags: ['REST', 'EDA', 'Java'], technology: 'Java / Spring Boot', deploymentStage: 'PRODUCTION', tps: 500 },
      responsibilities: ['Create orders', 'Track order status', 'Process fulfillment'],
    },
    {
      id: 'c-catalog-service',
      name: 'Catalog Service',
      shortName: 'CatSvc',
      description: 'Product catalog and inventory management',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-ecommerce',
      metadata: { maturity: 'MATURE', appType: 'WEB', tags: ['REST', 'RDMS', 'Java'], technology: 'Java / Spring Boot', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Manage product catalog', 'Track inventory'],
    },
    {
      id: 'c-user-db',
      name: 'User Database',
      shortName: 'UsrDB',
      description: 'Stores user profiles and authentication data',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-ecommerce',
      metadata: { maturity: 'MATURE', tags: ['RDMS', 'PII'], technology: 'PostgreSQL', deploymentStage: 'PRODUCTION', pii: true },
      responsibilities: ['Store user profiles', 'Authentication data'],
    },
    {
      id: 'c-order-db',
      name: 'Order Database',
      shortName: 'OrdDB',
      description: 'Stores order data and transaction history',
      kind: 'container',
      viewpoint: 'application',
      parentId: 's-ecommerce',
      metadata: { maturity: 'GROW', tags: ['RDMS'], technology: 'PostgreSQL', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Persist order records', 'Transaction history'],
    },
    {
      id: 'c-pricing-model',
      name: 'Pricing Model',
      shortName: 'PrcAI',
      description: 'ML model for dynamic pricing and discount recommendations',
      kind: 'aimodel',
      viewpoint: 'application',
      parentId: 's-ecommerce',
      metadata: { maturity: 'INTRO', tags: ['ML', 'Python'], technology: 'scikit-learn', deploymentStage: 'TESTING' },
      responsibilities: ['Dynamic pricing', 'Discount optimization', 'Demand forecasting'],
    },

    // ════════════════════════════════════════════════════════════════
    // APPLICATION viewpoint · component level  (component, retriever, evaluation, artifact, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'comp-order-controller',
      name: 'Order Controller',
      shortName: 'OrdCtrl',
      description: 'REST API controller handling order endpoints',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['REST', 'Java'], technology: 'Spring MVC' },
      responsibilities: ['Handle HTTP requests', 'Input validation', 'Response mapping'],
    },
    {
      id: 'comp-order-processor',
      name: 'Order Processor',
      shortName: 'OrdProc',
      description: 'Business logic for order validation, pricing, and state transitions',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['Java'], technology: 'Spring' },
      responsibilities: ['Validate orders', 'Calculate pricing', 'State transitions'],
    },
    {
      id: 'comp-event-publisher',
      name: 'Event Publisher',
      shortName: 'EvtPub',
      description: 'Publishes domain events to the message broker',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['EDA', 'Java'], technology: 'Spring / Kafka' },
      responsibilities: ['Publish domain events', 'Ensure delivery guarantees'],
    },
    {
      id: 'comp-order-repo',
      name: 'Order Repository',
      shortName: 'OrdRepo',
      description: 'Data access layer for order persistence',
      kind: 'component',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['RDMS', 'Java'], technology: 'Spring Data JPA' },
      responsibilities: ['CRUD operations', 'Query optimization'],
    },
    {
      id: 'comp-order-search',
      name: 'Order Search',
      shortName: 'OrdSrch',
      description: 'Semantic search across order history using embeddings',
      kind: 'retriever',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['ML'], technology: 'Elasticsearch' },
      responsibilities: ['Full-text order search', 'Fuzzy matching', 'Relevance ranking'],
    },
    {
      id: 'eval-order-accuracy',
      name: 'Order Accuracy Eval',
      shortName: 'OrdEval',
      description: 'Evaluates correctness of order processing pipeline',
      kind: 'evaluation',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['REST'] },
      responsibilities: ['Validate order completeness', 'Track error rates'],
    },
    {
      id: 'a-api-spec',
      name: 'OpenAPI Spec',
      shortName: 'OAS',
      description: 'API specification document for the Order Service',
      kind: 'artifact',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['REST'] },
      responsibilities: [],
    },
    {
      id: 'a-data-model',
      name: 'Domain Data Model',
      shortName: 'DataMdl',
      description: 'Entity-relationship diagram for the order domain',
      kind: 'artifact',
      viewpoint: 'application',
      parentId: 'c-order-service',
      metadata: { tags: ['REST'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // TECHNICAL viewpoint · container level  (container, aimodel, vectorstore, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'tc-message-broker',
      name: 'Message Broker',
      shortName: 'Kafka',
      description: 'Apache Kafka cluster for async event streaming',
      kind: 'container',
      viewpoint: 'technical',
      parentId: 's-ecommerce',
      metadata: { maturity: 'MATURE', tags: ['EDA'], technology: 'Apache Kafka 3.7', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Event streaming', 'Topic management', 'Consumer groups'],
    },
    {
      id: 'tc-redis-cache',
      name: 'Redis Cache',
      shortName: 'Redis',
      description: 'In-memory caching layer for session and catalog data',
      kind: 'container',
      viewpoint: 'technical',
      parentId: 's-ecommerce',
      metadata: { maturity: 'MATURE', tags: ['NoSQL'], technology: 'Redis 7', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Session caching', 'Rate limit counters', 'Catalog hot data'],
    },
    {
      id: 'tc-k8s-cluster',
      name: 'Kubernetes Cluster',
      shortName: 'K8s',
      description: 'Container orchestration for all microservices',
      kind: 'container',
      viewpoint: 'technical',
      parentId: 's-ecommerce',
      metadata: { maturity: 'GROW', tags: ['SOA'], technology: 'Kubernetes 1.29', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Service orchestration', 'Auto-scaling', 'Health checks'],
    },
    {
      id: 'tc-rec-model',
      name: 'Recommendation Model',
      shortName: 'RecAI',
      description: 'Neural collaborative filtering model for product recommendations',
      kind: 'aimodel',
      viewpoint: 'technical',
      parentId: 's-analytics',
      metadata: { maturity: 'INTRO', tags: ['ML', 'Python'], technology: 'PyTorch / TorchServe', deploymentStage: 'TESTING' },
      responsibilities: ['Generate recommendations', 'Model retraining pipeline', 'A/B serving'],
    },
    {
      id: 'tc-fraud-model',
      name: 'Fraud Detection Model',
      shortName: 'FrdAI',
      description: 'Real-time fraud scoring for payment transactions',
      kind: 'aimodel',
      viewpoint: 'technical',
      parentId: 's-payment',
      metadata: { maturity: 'GROW', tags: ['ML', 'Python'], technology: 'XGBoost / FastAPI', deploymentStage: 'PRODUCTION' },
      responsibilities: ['Transaction scoring', 'Feature extraction', 'Alert generation'],
    },
    {
      id: 'tc-product-vectors',
      name: 'Product Embeddings Store',
      shortName: 'ProdVec',
      description: 'Vector database storing product embeddings for similarity search',
      kind: 'vectorstore',
      viewpoint: 'technical',
      parentId: 's-analytics',
      metadata: { maturity: 'INTRO', tags: ['ML'], technology: 'Pinecone', deploymentStage: 'TESTING' },
      responsibilities: ['Store product vectors', 'Nearest-neighbor search', 'Index management'],
    },
    {
      id: 'tc-customer-vectors',
      name: 'Customer Embeddings Store',
      shortName: 'CustVec',
      description: 'Vector database for customer behavior embeddings',
      kind: 'vectorstore',
      viewpoint: 'technical',
      parentId: 's-analytics',
      metadata: { maturity: 'INTRO', tags: ['ML', 'PII'], technology: 'Weaviate', deploymentStage: 'TESTING', pii: true },
      responsibilities: ['Store customer vectors', 'Segment similarity', 'Privacy controls'],
    },
    {
      id: 't-deploy-event',
      name: 'Deployment Triggered',
      shortName: 'Deploy',
      description: 'CI/CD pipeline triggers container deployment',
      kind: 'trigger',
      viewpoint: 'technical',
      parentId: null,
      metadata: { tags: ['EDA'] },
      responsibilities: [],
    },

    // ════════════════════════════════════════════════════════════════
    // TECHNICAL viewpoint · component level  (component, retriever, artifact, trigger)
    // ════════════════════════════════════════════════════════════════
    {
      id: 'tcomp-kafka-consumer',
      name: 'Kafka Consumer',
      shortName: 'KfkCons',
      description: 'Consumes order events from Kafka topics',
      kind: 'component',
      viewpoint: 'technical',
      parentId: 'tc-message-broker',
      metadata: { tags: ['EDA', 'Java'], technology: 'Spring Kafka' },
      responsibilities: ['Consume messages', 'Offset management', 'Dead-letter handling'],
    },
    {
      id: 'tcomp-cache-manager',
      name: 'Cache Manager',
      shortName: 'CacheMgr',
      description: 'Manages cache invalidation and TTL policies',
      kind: 'component',
      viewpoint: 'technical',
      parentId: 'tc-redis-cache',
      metadata: { tags: ['NoSQL', 'Java'], technology: 'Lettuce / Spring Cache' },
      responsibilities: ['Cache invalidation', 'TTL policies', 'Cache-aside pattern'],
    },
    {
      id: 'tcomp-helm-charts',
      name: 'Helm Charts',
      shortName: 'Helm',
      description: 'Kubernetes deployment manifests and chart templates',
      kind: 'component',
      viewpoint: 'technical',
      parentId: 'tc-k8s-cluster',
      metadata: { tags: ['SOA'], technology: 'Helm 3' },
      responsibilities: ['Service templates', 'Config management', 'Release management'],
    },
    {
      id: 'tcomp-product-retriever',
      name: 'Product Retriever',
      shortName: 'ProdRet',
      description: 'Retrieves similar products from the vector store using embedding queries',
      kind: 'retriever',
      viewpoint: 'technical',
      parentId: 'tc-rec-model',
      metadata: { tags: ['ML', 'Python'], technology: 'LangChain / Pinecone Client' },
      responsibilities: ['Embedding lookup', 'Similarity threshold', 'Result ranking'],
    },
    {
      id: 'tcomp-customer-retriever',
      name: 'Customer Segment Retriever',
      shortName: 'CustRet',
      description: 'Queries customer embeddings to find similar customer segments',
      kind: 'retriever',
      viewpoint: 'technical',
      parentId: 'tc-rec-model',
      metadata: { tags: ['ML', 'Python'], technology: 'Weaviate Client' },
      responsibilities: ['Segment matching', 'Cohort analysis', 'Personalization'],
    },
    {
      id: 'ta-dockerfile',
      name: 'Dockerfile',
      shortName: 'Docker',
      description: 'Container image definition for the order service',
      kind: 'artifact',
      viewpoint: 'technical',
      parentId: 'tc-k8s-cluster',
      metadata: { tags: ['SOA'] },
      responsibilities: [],
    },
    {
      id: 'ta-ci-pipeline',
      name: 'CI Pipeline Config',
      shortName: 'CI',
      description: 'GitHub Actions workflow for build, test, and deploy',
      kind: 'artifact',
      viewpoint: 'technical',
      parentId: 'tc-k8s-cluster',
      metadata: { tags: ['SOA'] },
      responsibilities: [],
    },
  ],
  relationships: [
    // ── Business · Context ──
    { id: 'r1', sourceId: 'p-customer', targetId: 's-ecommerce', type: 'sync', label: 'Browses & purchases', protocol: 'HTTPS' },
    { id: 'r2', sourceId: 'p-admin', targetId: 's-ecommerce', type: 'sync', label: 'Manages products & orders', protocol: 'HTTPS' },
    { id: 'r2b', sourceId: 'p-support', targetId: 's-ecommerce', type: 'sync', label: 'Handles support tickets', protocol: 'HTTPS' },
    { id: 'r6', sourceId: 't-order-event', targetId: 's-notification', type: 'trigger', label: 'Triggers notification' },
    { id: 'r7', sourceId: 't-order-event', targetId: 's-analytics', type: 'trigger', label: 'Triggers analytics ingestion' },
    { id: 'r6b', sourceId: 't-refund-request', targetId: 's-payment', type: 'trigger', label: 'Initiates refund' },

    // ── Application · Context ──
    { id: 'r3', sourceId: 's-ecommerce', targetId: 's-payment', type: 'sync', label: 'Processes payments', protocol: 'HTTPS/REST' },
    { id: 'r4', sourceId: 's-ecommerce', targetId: 's-notification', type: 'async', label: 'Sends notifications', protocol: 'AMQP' },
    { id: 'r5', sourceId: 's-ecommerce', targetId: 's-analytics', type: 'dataflow', label: 'Streams events', protocol: 'Kafka' },
    { id: 'r5b', sourceId: 't-price-change', targetId: 's-ecommerce', type: 'trigger', label: 'Reprices catalog' },

    // ── Application · Container ──
    { id: 'r10', sourceId: 'c-web-app', targetId: 'c-api-gateway', type: 'sync', label: 'API calls', protocol: 'HTTPS' },
    { id: 'r11', sourceId: 'c-api-gateway', targetId: 'c-order-service', type: 'sync', label: 'Routes order requests', protocol: 'HTTP' },
    { id: 'r12', sourceId: 'c-api-gateway', targetId: 'c-catalog-service', type: 'sync', label: 'Routes catalog requests', protocol: 'HTTP' },
    { id: 'r13', sourceId: 'c-order-service', targetId: 'c-order-db', type: 'dataflow', label: 'Reads/writes orders' },
    { id: 'r14', sourceId: 'c-catalog-service', targetId: 'c-user-db', type: 'dataflow', label: 'Reads user prefs' },
    { id: 'r15', sourceId: 'c-order-service', targetId: 's-payment', type: 'sync', label: 'Payment processing', protocol: 'HTTPS' },
    { id: 'r16', sourceId: 'c-pricing-model', targetId: 'c-catalog-service', type: 'sync', label: 'Provides price suggestions' },
    { id: 'r17', sourceId: 'c-order-service', targetId: 'c-pricing-model', type: 'queries_model', label: 'Queries for pricing' },

    // ── Application · Component ──
    { id: 'r20', sourceId: 'comp-order-controller', targetId: 'comp-order-processor', type: 'sync', label: 'Delegates to' },
    { id: 'r21', sourceId: 'comp-order-processor', targetId: 'comp-event-publisher', type: 'async', label: 'Publishes events' },
    { id: 'r22', sourceId: 'comp-order-processor', targetId: 'comp-order-repo', type: 'sync', label: 'Persists orders' },
    { id: 'r23', sourceId: 'comp-order-repo', targetId: 'c-order-db', type: 'dataflow', label: 'SQL queries' },
    { id: 'r24', sourceId: 'comp-order-controller', targetId: 'a-api-spec', type: 'dependency', label: 'Implements' },
    { id: 'r25', sourceId: 'comp-order-search', targetId: 'comp-order-repo', type: 'retrieves', label: 'Searches orders' },
    { id: 'r26', sourceId: 'eval-order-accuracy', targetId: 'comp-order-processor', type: 'evaluates', label: 'Measures accuracy' },

    // ── Technical · Container ──
    { id: 'r30', sourceId: 'tc-message-broker', targetId: 'tc-k8s-cluster', type: 'dependency', label: 'Deployed on' },
    { id: 'r31', sourceId: 'tc-redis-cache', targetId: 'tc-k8s-cluster', type: 'dependency', label: 'Deployed on' },
    { id: 'r32', sourceId: 'tc-rec-model', targetId: 'tc-product-vectors', type: 'retrieves_from', label: 'Queries embeddings' },
    { id: 'r33', sourceId: 'tc-rec-model', targetId: 'tc-customer-vectors', type: 'retrieves_from', label: 'Queries customer segments' },
    { id: 'r34', sourceId: 'tc-fraud-model', targetId: 'tc-redis-cache', type: 'dataflow', label: 'Caches feature vectors' },
    { id: 'r35', sourceId: 't-deploy-event', targetId: 'tc-k8s-cluster', type: 'trigger', label: 'Triggers rolling update' },

    // ── Technical · Component ──
    { id: 'r40', sourceId: 'tcomp-kafka-consumer', targetId: 'tcomp-cache-manager', type: 'async', label: 'Invalidates cache on events' },
    { id: 'r41', sourceId: 'tcomp-product-retriever', targetId: 'tc-product-vectors', type: 'retrieves_from', label: 'Vector similarity query' },
    { id: 'r42', sourceId: 'tcomp-customer-retriever', targetId: 'tc-customer-vectors', type: 'retrieves_from', label: 'Segment lookup' },
    { id: 'r43', sourceId: 'tcomp-helm-charts', targetId: 'ta-dockerfile', type: 'dependency', label: 'References image' },
    { id: 'r44', sourceId: 'ta-ci-pipeline', targetId: 'tcomp-helm-charts', type: 'dependency', label: 'Deploys via Helm' },
  ],
  positions: [],
  views: [
    {
      id: 'v-biz-context',
      name: 'Business Overview',
      zoomLevel: 'context',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-biz-component',
      name: 'Business KPIs',
      zoomLevel: 'component',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-app-context',
      name: 'Application Landscape',
      zoomLevel: 'context',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-app-container',
      name: 'Application Architecture',
      zoomLevel: 'container',
      focusEntityId: 's-ecommerce',
      filters: {},
    },
    {
      id: 'v-app-component',
      name: 'Order Service Internals',
      zoomLevel: 'component',
      focusEntityId: 'c-order-service',
      filters: {},
    },
    {
      id: 'v-tech-container',
      name: 'Infrastructure Overview',
      zoomLevel: 'container',
      focusEntityId: null,
      filters: {},
    },
    {
      id: 'v-tech-component',
      name: 'Technical Internals',
      zoomLevel: 'component',
      focusEntityId: null,
      filters: {},
    },
  ],
  notes: [],
  boundaries: [],
};
